theme: jekyll-theme-cayman
title: 我的博客
description: 记录与分享的个人站点

collections:
  articles:
    output: true
    permalink: /_articles/:name.html

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: default
